#!/usr/bin/bash

cd ~/youtube;

if [ $# -eq 0 ];
then
    link=$(zenity --entry --text="Video:");
else
    link="$1";
fi

echo $link;
file=$(youtube-dl --get-filename $link)
echo $file;
echo;
if [ ! -f "$file" ];
then
    youtube-dl $link;
fi
echo;

mplayer "$file";
