if [ -z "$REMOTE_CONFIG_DIR" ]; then
    REMOTE_CONFIG_DIR="$HOME"
fi

shopt -s extglob
bind '\C-n:menu-complete'
bind '\C-p:menu-complete-previous'

export HISTCONTROL=ignoredups:ignorespace
export HISTFILESIZE= # unlimited
export HISTSIZE= # unlimited
shopt -s histappend


bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"
bind "set completion-ignore-case on"
bind "set menu-complete-display-prefix on"

source "$REMOTE_CONFIG_DIR/.aliases"

if which python3 > /dev/null; then
    export PS1="$(python3 ${REMOTE_CONFIG_DIR}/generateprompt.py)"
else
    export PS1="$(python ${REMOTE_CONFIG_DIR}/generateprompt.py)"
fi

export PATH="${REMOTE_CONFIG_DIR}/scripts:$PATH"

if [ $VAGRANT ]; then
   cd /vagrant
fi
