#!/usr/bin/python3

import subprocess
import socket

def run_capture(*args):
    return subprocess.run(args, stdout=subprocess.PIPE, universal_newlines=True)

def disable_monitors(monitors):
    arguments = []
    for monitor in monitors:
        arguments.append("--output")
        arguments.append(monitor)
        arguments.append("--off")
    run_capture("xrandr", *arguments)

def main():
    desktops = run_capture("bspc", "query", "-D", "--names").stdout.strip().split("\n")
    xrandr = run_capture("xrandr").stdout.split("\n")
    connected = [line.split()[0] for line in xrandr if not "disconnected" in line and "connected" in line]
    primary = [line for line in xrandr if "primary" in line][0].split()[0]
    secondary = [monitor for monitor in connected if monitor != primary]
    if len(secondary) > 0:
        disable_monitors(secondary)

    for desktop in desktops:
        run_capture("bspc", "desktop", desktop, "-m", primary)

if __name__ == "__main__":
    main()
