#!/usr/bin/python3

import subprocess
import socket
import sys
import time

logfile = open("/home/spi/bspwm_work.log", "w")
def log(*args, **kwargs):
    print(*args, file=logfile, *kwargs)
    print(*args, *kwargs)
    logfile.flush()

def run_capture(*args):
    log("running:", " ".join(args))
    return subprocess.run(args, stdout=subprocess.PIPE, universal_newlines=True)

# Yeah, I have no idea why that is the order?!
RIGHT = "DP-3" # the builtin
MID = "DP-0"
LEFT = "DP-4"

monitor_to_desktops = {LEFT: ("Ex1", "d1", "d2", "d5", "d6", "d7", "Ex1"), # left
                       MID: ("d3", "d4"),        # mid
                       RIGHT: ("d8", "d9", "d0", "Ex2", "Ex3")}   # right

def setup_monitors():
    xrandr = run_capture("xrandr",
                         "--output", MID, "--auto", "--left-of", RIGHT,
                         "--output", LEFT, "--auto", "--left-of", MID)
    return xrandr.returncode == 0

def setup_desktops():
    # Are the monitors setup correctly?
    monitors_output = run_capture("bspc", "query", "-M", "--names")
    monitors = [x for x in monitors_output.stdout.split("\n") if x]
    if (len(monitors) != 3 or any(monitor not in monitor_to_desktops for monitor in monitors)):
        return False

    # Setup desktops
    for monitor, desktops in monitor_to_desktops.items():
        for desktop in desktops:
            run_capture("bspc", "desktop", desktop, "-m", monitor)
    return True

def remove_unused():
    time.sleep(10)
    all_desktops = set()
    for desktops in monitor_to_desktops.values():
        all_desktops.update(desktops)
    current_desktops = run_capture("bspc", "query", "-D", "--names").stdout.strip().split("\n")
    for desktop in current_desktops:
        if desktop not in all_desktops:
            log("Removing desktop", desktop)
            run_capture("bspc", "desktop", desktop, "-r")

def is_at_work():
    hostname = socket.gethostname()
    return hostname == "LA0107" or hostname == "LA0158"

def work_config():
    run_capture("bspc", "config", "borderless_monocle", "false")
    run_capture("bspc", "config", "gapless_monocle", "false")

    run_capture("bspc", "config", "border_width", "2")
    run_capture("bspc", "config", "window_gap", "-2")
    for side in ("top", "right", "bottom", "left"):
        run_capture("bspc", "config", side+"_padding", "2")
    run_capture("bspc", "config", "paddingless_monocle", "true")



def main():
    if not is_at_work():
        log("ERROR: Not at work machine")
        sys.exit(1)

    work_config()

    if not setup_monitors():
        log("ERROR: Could not set up monitors")
        sys.exit(1)
    if not setup_desktops():
        log("ERROR: Could not set up desktops")
        sys.exit(1)
    remove_unused()
    sys.exit(0)

if __name__ == "__main__":
    main()
