#!/usr/bin/env bash

function fetch {
    url="$1"
    echo "$url"
    if curl -s -I "$url" | grep "200 OK"; then
        chromium --new-window "$url";
        exit;
    #     echo "open chromium"
    #     return 0;
    # else
    #     echo "dont open chromium"
    #     return 1;
    fi
}

# false ||
#     fetch "https://torvekoekken.dk/img/cms/menuer/Favorit%20uge%20$(date +%-V).pdf" ||
#     fetch "https://torvekoekken.dk/img/cms/Favorit%20uge%20$(date +%-V).pdf"

# fetch "https://torvekoekken.dk/img/cms/menuer/Favorit%20uge%20$(date +%-V).pdf"
# fetch "https://torvekoekken.dk/img/cms/Favorit%20uge%20$(date +%-V).pdf"
# fetch "https://torvekoekken.dk/Files/Images/Til%20ugens%20menu/Menuer%20Favorit/Favorit%20uge%20$(date +%-V).pdf"

# evince "https://torvekoekken.dk/Files/Images/Til%20ugens%20menu/Menuer%20Favorit/Favorit%20uge%20$(date +%-V).pdf" --page-index="$(date +%u)"
evince "https://torvekoekken.dk/Files/Images/Til%20ugens%20menu/Menuer%20Favorit/Favorit%20uge%20$(date +%-V)%202018.pdf"  --page-index="$(date +%u)"
