#!/bin/sh

cd ~

files=(
    # directories:
    '.emacs.d'
    '.config/bspwm'
    '.config/sxhkd'
    'code/scripts'
    # files:
    '.Xdefaults'
    '.Xmodmap'
    '.aliases'
    '.bashrc'
    '.git_prompt.zsh'
    '.nanorc'
    '.xinitrc'
    '.zshrc'
);

for file in "${files[@]}"
do
    ln -s "config/$file" "$file"
done
