#!/usr/bin/env sh

scrot /tmp/screen_locked.png
convert /tmp/screen_locked.png -blur 20x20 /tmp/screen_locked_blurred.png
rm /tmp/screen_locked.png

before=$(date "+%Y-%m-%d %H:%M:%S")
echo "$before locked screen" >> ~/work.log
killall -SIGUSR1 dunst # Pause dunst
i3lock -i /tmp/screen_locked_blurred.png
killall -SIGUSR2 dunst # Resume dunst
after=$(date "+%Y-%m-%d %H:%M:%S")
echo "$after unlocked screen" >> ~/work.log
