#!/usr/bin/env sh

# If the script is called with one argument and it is a file, less is called, else ls is called

if [ "$#" -eq 1 ] && [ -f "$1" ] ; then
    less "$@"
else
    ls  -CF --group-directories-first --color=auto "$@";
fi
