#!/usr/bin/env python3

import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("zipfile")
    parser.add_argument("inner", nargs="?", default=None)
    args = parser.parse_args()

    if args.inner is None:
        subprocess.run(["unzip", "-Z", args.zipfile])
    else:
        subprocess.run(["unzip", "-c", args.zipfile, args.inner])


if __name__ == "__main__":
    main()
