#!/usr/bin/perl
$num = $#ARGV + 1;
print "$num\n";

if ($num == 1) {
    $printer = "s2a";
    $file = @ARGV[0];
} elsif ($num == 2) {
    $printer = @ARGV[0];
    $file = @ARGV[1];
}
else{
    print "Wrong number of arguments, use: print PRINTER FILE\n";
    exit 1;
}
exec("ssh caroline\@tyr.diku.dk lp -d $printer < $file");
