#!/usr/bin/env bash

export NO_AT_BRIDGE=1 # Makes Emacs not throw the warning: ** (emacs:3616): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus

# # (setq ps-landscape-mode t) Does not work?
# echo "$1"
# if [ -z $2 ]; then
#     emacs -Q "$1" --eval "(progn (set-face-attribute 'default nil :height 90) (when (derived-mode-p 'outline-mode) (outline-show-all)) (setq ps-paper-type (quote a4)) (setq ps-right-margin 20) (setq ps-left-margin 20) (ps-print-buffer-with-faces) (save-buffers-kill-terminal))"
# else
#     # Print to pdf $2
#     # TEMP=$(mktemp -d)
#     # PSFILE="$TEMP/out.ps"
#     PSFILE="$2"
#     emacs -Q "$1" --eval "(progn (set-face-attribute 'default nil :height 90) (when (derived-mode-p 'outline-mode) (outline-show-all)) (setq ps-paper-type (quote a4)) (setq ps-right-margin 20) (setq ps-left-margin 20) (ps-print-buffer-with-faces \"$PSFILE\") (save-buffers-kill-terminal))"
#     # ps2pdf "$PSFILE" "$2"
#     # rm -r "$TEMP"
# fi

FILE="$1"
if [ -z $2 ]; then
    # when output is nil, will print to default printer else it will print as a pdf
    OUTPUT="nil"
else
    # the string containing the output
    OUTPUT="\"$2\""
fi
COMMAND=$(cat <<-EOF
(progn
  (defun my-ps-header-dirpart ()
      (if (string-prefix-p "/tmp/" (buffer-file-name))
          ""
        (let ((fname (buffer-file-name)))
          (if fname
              (if (string-equal (buffer-name) (file-name-nondirectory fname))
                  (abbreviate-file-name (file-name-directory fname))
                fname)
            ""))))
  (setq ps-left-header '(ps-get-buffer-name 'my-ps-header-dirpart))
  (set-face-attribute 'default nil :height 90)
  (when (derived-mode-p 'outline-mode)
    (outline-show-all))
  (setq ps-paper-type 'a4)
  (setq ps-right-margin 20)
  (ps-print-buffer-with-faces $OUTPUT)
  (setq ps-left-margin 20)
  ;;(kill-emacs)
  )
EOF
       )

emacs -Q "$FILE" --eval "$COMMAND"
