#!/usr/bin/env bash

case "${1,,}" in
    "playpause")
        command="PlayPause";
        ;;
    "pause")
        command="PlayPause";
        ;;
    "play")
        command="PlayPause";
        ;;
    "stop")
        command="Stop";
        ;;
    "next")
        command="Next";
        ;;
    "previous")
        command="Previous"
        ;;
    "prev")
        command="Previous"
        ;;
    *)
        echo "Invalid argument $1";
        exit 1;
esac
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 "org.mpris.MediaPlayer2.Player.${command}"



# dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'
# dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Position'
