#!/usr/bin/bash

cd ~/youtube;

if [ $# -eq 0 ];
then
    link=$(zenity --entry --text="Video:");
else
    link="$1";
fi

if [[ -z $link ]]
then
    file=$(ls -c *.mp4 | head -n 1)
else
    echo $link;
    file=$(youtube-dl --get-filename $link)
    echo $file;
    echo;
    if [ ! -f "$file" ];
    then
        youtube-dl $link;
    fi
    echo;
fi

mplayer "$file";
