;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        back-to-indentation-or-beginning
        backward-kill-word-to-newline
        backward-word-to-newline
        forward-kill-word-to-newline
        forward-word-to-newline
        indent-for-tab-command
        maple-untab
        new-indented-line
        pager-row-down
        python-backspace
        toggle-letter-case
        yank-or-pop
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-mode
        ))
