;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        org-delete-backward-char
        org-self-insert-command
        python-indent-dedent-line-backspace
        xpdfremote/xpdf-pageDown
        yank-or-pop
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-backspace
        iedit-mode
        ))
